name: Run Unit Tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    name: Unit Tests (JUnit + Mockito)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 25
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -f backend/pom.xml clean install

      - name: Upload Test Report (Surefire)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: unit-test-report
          path: target/surefire-reports/
